### ISSUE TITLE
Unify building assets

### ISSUE THREAD

**Issue by shyim** [FriendsOfShopware/shopware-cli#203]
### Please describe the feature you would like to see implemented.

```[tasklist]
### Tasks
- [x] Get rid of calling `bundle:dump` and `feature:dump` and use our Go equal code
- [x] Use `extension.BuildAssetsForExtensions` instead of calling NPM in Commands
- [x] Add ability to `extension.BuildAssetsForExtensions` to build only Storefront or Administration using AssetConfig
```
